apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: TXlzcWxBZG1pbg==
  MYSQL_DATABASE: R29uZURC
  MYSQL_USER: YWRtaW4=
  MYSQL_PASSWORD: TXlzcWxBZG1pbg==