apiVersion: v1
kind: Namespace
metadata:
  name: gone-database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: gone-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage  # Ensure it matches the PV
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: gone-mysql
spec:
  replicas: 1  # Ensure only one instance to avoid storage conflicts
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          envFrom:
            - secretRef:
                name: mysql-secret
          ports:
            - containerPort: 3308
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
      tolerations:   # Allows scheduling on control-plane if needed
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: gone-mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3308
      targetPort: 3306
  type: ClusterIP
