apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: gone-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: tiesd01/spring-app:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-config
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 2001
      targetPort: 8080
  type: ClusterIP
